theme: jekyll-theme-slate
title: FACT - The Firmware Analysis and Comparison Tool
description: The Firmware Analysis and Comparison Tool (FACT) is intended to automate Firmware Security analysis (Router, IoT, UEFI, Webcams, Drones, …). Thereby it shall be easy to use (web GUI), extend (plug-in system) and integrate (REST API).
